
server:
  port: 8101

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#     defaultZone: http://admin:hqjymicro@10.0.98.17:8100/eureka/,http://admin:hqjymicro@10.0.98.17:8102/eureka/
      defaultZone: http://admin:jenpin@eks-master:8100/eureka/
  instance:
    hostname: eks-slave1 #hqjy.eks.slave1  ${spring.cloud.client.ipAddress}

logging:
  path: ./logs
  file: application-slave1.log