
server:
  port: 8100

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://admin:hqjymicro@10.0.98.17:8101/eureka/,http://admin:hqjymicro@10.0.98.17:8102/eureka/
      defaultZone: http://admin:jenpin@eks-slave1:8101/eureka/
  instance:
    hostname: eks-master  #  ${spring.cloud.client.ipAddress}

logging:
  path: ./logs
  file: configserver-master.log