server:
  tomcat:
    max-threads: 800    # tomcat最大线程数，默认为200
    uri-encoding: utf-8   # tomcat的URI编码
    basedir: ./tmp   # 存放Tomcat的日志、Dump等文件的临时文件夹

spring:
  profiles:
    active: single   #master   slave1 single
  application:
    name: eureka-server

security:
  basic:
    enabled: true # 启用认证
  user:
    name: admin
    password: jenpin

eureka:
  environment: Jenpin
  datacenter: 服务发现与注册中心
  server:
    enable-self-preservation: false  # 关闭自我保护机制
    #wait-time-in-ms-when-sync-empty: 0 #在Eureka服务器获取不到集群里对等服务器上的实例时，需要等待的时间，单位为毫秒，默认为1000 * 60 * 5
    response-cache-auto-expiration-in-seconds: 60 #eureka 注册表换存过期时间，默认为180秒
    eviction-interval-timer-in-ms: 4000 #清理间隔（单位毫秒，默认是60*1000）这里指定EvictionTask定时任务的调度频率，用于剔除过期实例
    peer-node-connect-timeout-ms: 1000 #连接eureka对等节点服务器复制的超时的时间（默认200ms）
    peer-node-read-timeout-ms: 600 #读取eureka对等节点服务器复制的超时的时间（默认200ms）
  instance:
#    prefer-ip-address: true   #   IP就是注册到Eureka Server上的IP 而不是hostname
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}