server:
  tomcat:
    max-threads: 800    # tomcat最大线程数，默认为200
    uri-encoding: utf-8   # tomcat的URI编码
    basedir: ./tmp   # 存放Tomcat的日志、Dump等文件的临时文件夹

spring:
  profiles:
    active: single   #master   slave1 single
  application:
    name: eureka-server

security:
  basic:
    enabled: true # 启用认证
  user:
    name: admin
    password: jenpin

eureka:
  environment: Jenpin
  datacenter: 服务发现与注册中心
  server:
    enable-self-preservation: false  # 关闭自我保护机制
    eviction-interval-timer-in-ms: 4000 #清理间隔（单位毫秒，默认是60*1000）
  instance:
#    prefer-ip-address: true   #   IP就是注册到Eureka Server上的IP 而不是hostname
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}