
server:
  port: 8102

eureka:
  client:
    service-url:
#      defaultZone: http://admin:hqjymicro@10.0.98.17/:8100/eureka/,http://admin:hqjymicro@10.0.98.17:8101/eureka/
      defaultZone: http://admin:hqjymicro@hqjy.eks.master:8100/eureka/,http://admin:hqjymicro@hqjy.eks.slave1:8101/eureka/
  instance:
    hostname: hqjy.eks.slave2 #      ${spring.cloud.client.ipAddress}
logging:
  path: ./logs
  file: application-slave2.log