
server:
  port: 8100

eureka:
  client:
    service-url:
#      defaultZone: http://admin:hqjymicro@10.0.98.17:8101/eureka/,http://admin:hqjymicro@10.0.98.17:8102/eureka/
      defaultZone: http://admin:hqjymicro@micro2:8101/eureka/
  instance:
    hostname: micro1  #hqjy.eks.master  ${spring.cloud.client.ipAddress}

logging:
  path: ./logs
  file: configserver-master.log