server:
  port: 8500

spring:
  application:
    name: api-gateway         # 指定配置中心配置文件的{application}

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:micro-service@jenpin.eks.master:8100/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

app:
  msg: this is test msg

zuul:
  routes:
    api-gateway: /gateway/**  #方式一
    gateway:
      path: /api-gateway/**   #方式二
      service-id: api-gateway
