spring:
  application:
    name: micro-grpc-server
  cloud:
    bus:
      trace:
        enabled: true   # 开启消息跟踪
  sleuth:
    sampler:
      percentage: 1
  rabbitmq:
    host: 10.0.98.17
    port: 5672                                    # 注意端口是5672，不是15672
    username: hqjy
    password: hqjy2017

server:
  port: 9801
grpc:
  server:
    port: 9991

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:micro-service@jenpin.eks.master:8100/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true                     # 设置微服务调用地址为IP优先（缺省为false）