server:
  port: 8600

zipkin:
  storage:
    type: elasticsearch #表示zipkin数据存储方式是elasticsearch
    elasticsearch:
      cluster: elasticsearch
      hosts: http://localhost:9200
      index: zipkin
      index-shards: 5
      index-replicas: 1
spring:
  application:
    name: micro-sleuth-server
  rabbitmq:
    host: 10.0.98.17
    port: 5672                                    # 注意端口是5672，不是15672
    username: guest
    password: guest
  sleuth:
    enabled: false  #表示当前程序不使用sleuth

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:jenpin@idrinkjava.cn:8100/eureka/
  instance:
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
      prefer-ip-address: true                     # 设置微服务调用地址为IP优先（缺省为false）