spring:
  application:
    name: micro-cloud-bus
  cloud:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

server:
  port: 8400

eureka:
  client:
    service-url:
      defaultZone: http://admin:micro-service@jenpin.eks.master:8100/eureka/

management:
  security:
    enabled: false
